- hosts: mis
  serial: 1
  vars:
    http_port: 8080
    app: mis
    version_page: "version"
    group_id_app: com.rhapsody.ecomm
    artifact_id_app: mis
    group_id_config: com.rhapsody.ecomm
    artifact_id_config: mis-config
    repository_url: "{{ maven_repo }}"
  
  tasks:

  - maven_artifact:
     group_id: "{{ group_id_config }}"
     artifact_id: "{{ artifact_id_config }}"
     extension: tar
     classifier: "{{ deploy_environment }}"
     repository_url: "{{ repository_url }}"
     dest: ~/mis-config.tar
     version: "{{ config_version }}"

  - name: deploy config
    command: "{{ item }}"
    with_items:
       - sudo mkdir -p /var/tom8080/conf/backup
       - sudo rsync -ra /var/tom8080/conf/mis/ /var/tom8080/conf/backup
       - sudo tar xvf ~/mis-config.tar -C /var/tom8080/conf/mis/

  - maven_artifact:
     group_id: "{{ group_id_app }}"
     artifact_id: "{{ artifact_id_app }}"
     extension: war
     repository_url: "{{ repository_url }}"
     dest: ~/mis.war
     version: "{{ app_version }}"
  
  - name: remove 
    command: sudo rm -Rf  /var/tom8080/webapps/mis

  - name: copy
    command: sudo mv ~/mis.war /var/tom8080/webapps/mis.war

  - name: restart
    command: sudo /etc/init.d/tomcat 8080 restart
    async: 300
    poll: 5
    register: release_output

  - debug: var=release_output.stdout
  
  - pause: seconds=10


  - name: wait log show complete
    command: tail -2000 /var/tom8080/logs/catalina.out
    register: log_output
    until: log_output.stdout.find("Server startup") > -1
    retries: 120
    delay: 10

  - name: wait port {{ http_port }} open
    wait_for: "host={{ inventory_hostname }} port={{ http_port }} delay=15"
    delegate_to: 127.0.0.1

  - name: "wait version page return"
    uri:
      url: "http://{{ inventory_hostname }}:{{ http_port }}/{{ app }}/{{ version_page }}"
      status_code: 200
      register: result
      until: result.status == 200
      retries: 240
      delay: 10
    delegate_to: 127.0.0.1
